### ISSUE TITLE
I just want to know how do I add a js function dynamicly when I add a nested form

### ISSUE THREAD

**Issue by lostpupil** [ncri/nested_form_fields#11]
```
$(document).on "fields_added.nested_form_fields", (event,param) ->
  console.log "INFO: Fields were successfully added, callback not handled."
  return
```
so how can I get the last added element like below 
`$('.element').select2()`
for each element?

**Comment by vanetten** [comment]
$(document).on "fields_added.nested_form_fields", (event, param) ->
	$("#profile_practices_attributes_" + param.added_index + "_user_ids").select2
    placeholder: "Add Office Manager(s)"
    allowClear: true
