### ISSUE TITLE
When using this gem in an edit page, it'll create, not update nested records.

### ISSUE THREAD

**Issue by rocLv** [ncri/nested_form_fields#18]

**Comment by karimmtarek** [comment]
I had the same issue, when I first tried to update one of the nested skills, all of them got created again, my strong params were like this:
```
params.require(:user).permit(..., skills_attributes: [:name])
```
following @jsgarvin comment, I added the 'id' and '_destroy' to the strong params, now its working like a charm
```
params.require(:user).permit(..., skills_attributes: [:id, :name, :_destroy])
```
@ncri I didn't really add any hidden fields to make it work.
