### ISSUE TITLE
Not working in rails 4 with custom rails engine

### ISSUE THREAD

**Issue by loganathan-s** [ncri/nested_form_fields#21]
I am getting the below error, where ManagementPublicIp is a model from my custom rails engine

Model:
  has_many :management_public_ips, class_name: "IpamServer::ManagementPublicIp"
  accepts_nested_attributes_for :management_public_ips, allow_destroy: true

ERROR"
ActionView::Template::Error (uninitialized constant ManagementPublicIp):
    85:     .col-lg-9
    86:       = f.check_box :filtering_enabled, :class => 'form-control'
    87: 
    88:   = f.nested_fields_for :management_public_ips do |ff|
    89:     = ff.remove_nested_fields_link
    90:     = ff.text_field :ip, :class => 'form-control'
    91:     = f.add_nested_fields_link :management_public_ips

**Comment by ncri** [comment]
Looks like the engine namespace is stripped off. I will look into it when I have some time. Also pull requests are welcome. :)

**Comment by loganathan-s** [comment]
No need of change in the code,  for module we need to pass the class name option as like below

= f.nested_fields_for :management_public_ips, class_name: "ipam_server/management_public_ip" do |ff|

CODE IN GEM:
association_class = (options[:class_name] || association_name).to_s.classify.constantize

**Comment by ncri** [comment]
Oh, glad you found out. So long ago I wrote this! ;-)
