### ISSUE TITLE
Model conversion doesn't take relation class name into account

### ISSUE THREAD

**Issue by jensljungblad** [ncri/nested_form_fields#23]
I have these two relationships:

```ruby
has_many :comparisons
has_many :foo_comparisons, -> { where(comparable_type: "index") }, class_name: "Comparison"
```

If I do
```ruby
f.nested_fields_for :foo_comparisons
```

It tries to load a `FooComparison` constant, which doesn't exist, instead of going through the `class_name` of the relation. I believe this works in nested_forms.

**Comment by ncri** [comment]
I think someone had a similar issue recently. I think you need to add the class name as a parameter to nested_fields_for. Try

    f.nested_fields_for :foo_comparisons, class_name: "Comparison"

Or try:

    f.nested_fields_for :foo_comparisons, your_object.foo_comparisons

**Comment by jensljungblad** [comment]
Ah, thanks!
