### ISSUE TITLE
How to access the underlying object within nested forms?

### ISSUE THREAD

**Issue by nateq314** [ncri/nested_form_fields#24]
How do I access the underlying object (for example @post, @attachment, etc.) in templates? The form is working fine, no bugs, I just need to write some conditional expressions in the template to display it differently based on the data stored in the object that is referenced by the nested form. But the documentation doesn't seem to say anything about this.
Nathan

**Comment by ncri** [comment]
Well, you can use f.object (in case your form builder object is f). It's not in the nested_form_fields docs, because it is not specific to this gem, but rather works with all rails form builders.

**Comment by nateq314** [comment]
Thanks! Had suspected there was such a method for form builders but even the Rails API docs say almost nothing about it.
