### ISSUE TITLE
Table friendy

### ISSUE THREAD

**Issue by kindell** [ncri/nested_form_fields#25]
Hi,
I try to use `nested_form_fields` in a `<table>`. But when I place the `<tr>` and `<td>` tags in a `nested_fields_for`, weird stuff happen. First of, my `remove_nested_fields_link` stops working. And when try I to add a new element through the `add_nested_fields_link`, the new element doesn't get wrapped with a `<tr>` and `<td>` tag which would be my expectations.

Is it possible to make `nested_form_fields` play nice with tables?

**Comment by ncri** [comment]
Try using `wrapper_tag: :tr` and put the td's inside the nested fields without an extra tr.

**Comment by kindell** [comment]
Thanks, works great!
