### ISSUE TITLE
how to access the index attribute for each nested form?

### ISSUE THREAD

**Issue by nateq314** [ncri/nested_form_fields#26]
I have the following

form_for(@user) do |f|
   ...template code for each user...
   f.nested_fields_for :attendees do |ff|
      ...template code for each attendee...

and I just want to access the index of each attendee in order to create customized classes, ids, etc. Would have thought this would be ff.index (I saw there's an index attribute for the FormBuilder rails class). But when I use this in code, it outputs nothing. Am I doing something wrong?

**Comment by ncri** [comment]
I had trouble with this once (actually not a nested_form_fields issue). I use this as a workaround (example in slim):

    = f.nested_fields_for :posts do |fp|
      - post_index = object.posts.index(fp.object)

**Comment by ncri** [comment]
Did you get it working?
