### ISSUE TITLE
Trigger event on element instead of document

### ISSUE THREAD

**Issue by Linuus** [ncri/nested_form_fields#30]
Hi!

Would it be possible to trigger the removed and added events on the removed/added element instead of on document? This would make it a bit easier to make sure you are handling the correct events. Now you have to find the added or removed element, check if it has the correct type and then do what you want to do.

I believe this is how Ryan Bates' nested_form gem works.

**Comment by ncri** [comment]
Well, this is helping https://github.com/ncri/nested_form_fields/pull/27

I think i have never needed the events myself, so I haven't thought about what is most useful. 

You could supply a pull request. But I think it would be good if we stay backwards compatible, unless there is a good reason not to.

**Comment by Linuus** [comment]
Ok, let me give you small example.

If you have two types of nested fields in a form, `foo` and `bar`. Also, you have a generic plugins which handles sorting of the added items.

```erb
<div class="sortable">
  <%= f.nested_fields_for :foo  do |ff| %>
     ...
  <% end %>
</div>

<div>
  <%= f.nested_fields_for :bar  do |ff| %>
     ...
  <% end %>
</div>
```

When a field is added, I want to sort the items. I only want to do this if the items are sortable.
When the events are triggered on `document` I need to do stuff like this:

```javascript
$(document).on("fields_added.nested_form_fields", function(event, param) {
  var $sortable = $(".nested_" + param.association_path + ":last").parents(".sortable");
  if($sortable.length === 0) return;
  setSortPositions($sortable);
});

$(document).on("fields_removed.nested_form_fields", function(event, param) {
  var $sortable = $("[name='" + param.delete_association_field_name + "']").parents(".sortable");
  if($sortable.length === 0) return;
  setSortPositions($sortable);
});
```
Those checks if elements exists are quite annoying to write everytime you need to listen on the events. (Maybe there is a better way to do it?)

In Ryans nested_form gem, you can instead write something like this:
```javascript
...
$element.on('nested:fieldAdded nested:fieldRemoved', function(event) {
  setSortPositions($(event.target));
});
...
```
(where `$element` is set up when you initialize your js)

Do you understand my use case?

**Comment by ncri** [comment]
Yes. Have you checked #27? You don't have to use `:last`, you can use the index passed along in the event. I don't see, why you would need to check for the existence of the element then.

But I like your suggestion of firing the event on the actual list container. Seems like a better solution to me. You are welcome to create a pull request.

**Comment by Linuus** [comment]
Yes, I saw #27. I don't think it helps in this case though. I'm checking if the element i wrapped in an element with the class `.sortable` to know if the event was actually triggered by a sortable thing. If I could create listeners on the actual list container, I'd know that the event was triggered by a sortable thing.

I'll try to wrap up a PR as soon as I get the time :+1:

**Comment by ncri** [comment]
Ah, got it now. Thx.
