### ISSUE TITLE
How do I use an index?

### ISSUE THREAD

**Issue by joost** [ncri/nested_form_fields#32]
Rails allows me to do something like:

    <%= person_form.fields_for :projects do |project_fields| %>
      Project #<%= project_fields.index %>

(See: http://api.rubyonrails.org/classes/ActionView/Helpers/FormBuilder.html)

Is there a way I can use the .index method in nested_form_fields?

**Comment by joost** [comment]
FYI I would like to do something like:

    <%= f.remove_nested_fields_link('Remove', class: 'btn btn-danger') if f.index > 0 %>

**Comment by ncri** [comment]
Nested fields *should* supply the same functionality as the normal rails form builder.

**Comment by joost** [comment]
hmm.. maybe it is because I'm using https://github.com/plataformatec/simple_form

**Comment by ncri** [comment]
Well, there are some issues with getting the index. I now remember I posted a suggestion in this issue:

https://github.com/ncri/nested_form_fields/issues/26

See my first comment.

**Comment by joost** [comment]
Guess that would work. Thanks for the suggestion!
So it would be something like:

    <% index = f.object.index(ff.object) %>
    <%= ff.remove_nested_fields_link('Remove', class: 'btn btn-danger') if index && index > 0 %>

However I found a different problem .. since removing the 'remove' button will also remove it from the generate jquery template.

**Comment by ncri** [comment]
Nope, that would not work you will have to call the has_many association on f.object:

    <% index = f.object.your_nested_has_many_association.index(ff.object) %>

If would hide the first link in the fields list with javascript.

**Comment by joost** [comment]
Thx!

**Comment by arturaum** [comment]
This solution
`<% index = f.object.your_nested_has_many_association.index(ff.object) %>`
doesn't work, if you use "add" link
