### ISSUE TITLE
Get the link clicked in the fields_added.nested_form_fields event

### ISSUE THREAD

**Issue by jensljungblad** [ncri/nested_form_fields#33]
Would it be possible to get the original click event together with the `fields_added.nested_form_fields` event?

I have two different `add_nested_fields_link` links, and I would like to know which one was clicked.

```coffee
$('body').on 'click', '.add_nested_fields_link', (originalEvent) ->
  ...
  $parsed_template.trigger("fields_added.nested_form_fields", {object_class: object_class, added_index: added_index, association_path: association_path, originalEvent: originalEvent});
```

Or something like that

**Comment by ncri** [comment]
The event is triggered on the element added since this pull request:

https://github.com/ncri/nested_form_fields/pull/31

From that element you should be able to find the connected add_nested_fields_link.

**Comment by jensljungblad** [comment]
Sorry, I wasn't very clear.

I have two buttons for the same nested fields. Something like this:

```ruby
f.nested_form_fields :containers do |ff|
  ...
end

f.add_nested_fields_link :containers, "Add foo-container", data: { behavior: "add-foo-container" }
f.add_nested_fields_link :containers, "Add bar-container", data: { behavior: "add-bar-container" }
```

And I would like to know which of the two buttons was clicked.

That being said, perhaps the problem I'm trying to solve can be solved in some other way. Basically, I have an association that in turn has a polymorphic association. I was thinking perhaps this is beyond the scope of this gem which is why I was trying to use js to overcome the problem. My scenario looks something like this:

```ruby
class Article < ActiveRecord::Base
  has_many :containers
end

class Container < ActiveRecord::Base
  belongs_to :article
  belongs_to :content, polymorphic: true
end

class Text < ActiveRecord::Base
  has_one :container
end

class Image < ActiveRecord::Base
  has_one :container
end
```

```ruby
form_for @article do |f|
  f.text_field :title
  ...

  f.nested_fields_for :containers do |ff|
    ff.text_field :title
    ff.fields_for :content do |fff|
      case fff.object.class
      when Text
        fff.text_area :body
      when Image
        fff.text_field :image_url
      end
    end
  end
  f.add_nested_fields_link :containers, "Add container"
end
```

Now, editing existing containers works well, but adding a new one is problematic, because its `content` is polymorphic, so `nested_form_fields` can't really know what to put in its "blueprint". This is what I was trying to work around using the above technique with two `add_nested_fields_link` buttons: one for each content type. If there's a better way to do this I would love to hear it :)

**Comment by ncri** [comment]
Oh, well, yes, you are right, it's a tricky situation. The form in your example will not work properly, yes, for the reasons you describe. Actually I can't quite imagine how you would get this work with two buttons either. Because you would need to give 2 "blueprints" of your items, which is not supported.
Maybe you could add all potential object fields and only show the ones needed for the current object. Seems tricky and you would need to use for example `text_area_tag` instead of `fff.text_area`.

**Comment by lessless** [comment]
maybe it's possible to send an original JQuery event object in the params?

**Comment by ncri** [comment]
The original event is now passed along, thanks to https://github.com/ncri/nested_form_fields/pull/34 from @lessless

**Comment by jensljungblad** [comment]
Perfect, thanks :+1:
