### ISSUE TITLE
Using rails data confirm on remove links

### ISSUE THREAD

**Issue by jensljungblad** [ncri/nested_form_fields#37]
Would it be possible to add support for rails `data-confirm` on remove links?

```erb
<%= f.remove_nested_fields_link data: { confirm: "Are you sure?" } %>
```

**Comment by ncri** [comment]
Hm, I don't see why not. Would you like to supply a pull request? ;-)

**Comment by jensljungblad** [comment]
I can give it a try, sure. You have any ideas about how to do it? :)

**Comment by ncri** [comment]
You need to look for the data-confirm attribute in the remove_nested_fields_link click handler `$('body').on 'click', '.remove_nested_fields_link'` 

Looking at this I just noticed that there is a bug. When no class is specified a class "{}" is added to the remove link. Will fix it when I have a minute.
