### ISSUE TITLE
Coffee rails dependency

### ISSUE THREAD

**Issue by jensljungblad** [ncri/nested_form_fields#42]
`coffee-rails` was added as a dependency in this commit: https://github.com/ncri/nested_form_fields/commit/a80487f4844cdfc32db62692a013c5435683f0a5

In newer rails projects the gemfile depends on `gem "coffee-rails", "~> 4.1.0"` and nested form fields cannot be installed. Can the dependency be made more forgiving?

**Comment by ncri** [comment]
Oh, yeah, I overlooked that, we should change it...

**Comment by ncri** [comment]
Loosened it: https://github.com/ncri/nested_form_fields/commit/271a80f0a4b214230b3cdc6022193662a05bf9d5
