### ISSUE TITLE
How to start showing fieldset

### ISSUE THREAD

**Issue by lymecca** [ncri/nested_form_fields#44]
Is it possible to configure to start showing one fieldset?

**Comment by ncri** [comment]
Not sure what you mean. You mean when there are several has_many association records to show only the first form? In that case you would have to use javascript. nested_for_fields behaves like fields_for, which displays all associated records by default.

You could do something like:

    f.nested_fields_for :your_associations, [your_model.your_associations.first] do

But not sure if that is what you want?

**Comment by lymecca** [comment]
oh! My apologize, my English is poor. Let me try to explain...

I configured the gem as mentined in the Installation section. Now, whem user get the form, from /new page, the user will have a link "+ add" for the nested fields, I wanna that, the nested field, appears without the user click to "+ add" and, if the user need more, them him click on "+ add", otherwise, click o "remove".

**Comment by lymecca** [comment]
Sorry for that...
I forgot to include the @base_product.products.build in the new action of base_product controller.
