### ISSUE TITLE
nesting nested forms

### ISSUE THREAD

**Issue by xangelux** [ncri/nested_form_fields#45]
Is there a way to nest inside a nested form? I have a dynamic Survey application and want to have it add options for the answers, so I have a form.nested_fields_for and that works great but inside that, I have another nested_fields_for for the options. When I click to add a new question, It adds the question form (with no errors) and one fields_for for the options but the link to add options doesn't add any more options and the current last option (the one added by the add link for the questions) is constructed funny, so is rejected (by strong params) Is that a bug or it cannot add nested in nested form?

I hope I made myself clear, if not, please let me know.

**Comment by ncri** [comment]
You can nest as deep as you want with nested_form_fields. Would need to see your code to see what's wrong. Do you get any javascript errors? You can check with chrome's developer console for example.

**Comment by xangelux** [comment]
yeah, sorry, it was my code.
