### ISSUE TITLE
Works in edit but not new form

### ISSUE THREAD

**Issue by rschooley** [ncri/nested_form_fields#47]
I am inheriting a project with a form with nested_form_fields.

The edit form for an existing model adds the child markup, but the new does not.  

* The collection proxy is present in both scenarios
* It does not throw a JS error
* `fields_adding.nested_form_fields` doesn't show an issue
* `fields_added.nested_form_fields` doesn't show an issue

Looking at the rendered content:
* When editing we get a `fieldset` and a `script` tag
* When adding new we only get a `script` tag

The form:
```
= form_for [:foo, bar] do |f|
  # top level bar stuff
    
  .form-group
    f.nested_fields_for :bazs do |ff|
      = ff.label :name
      = ff.text_field :name

  = f.add_nested_fields_link :bazs
```

**Comment by ncri** [comment]
Did you make sure you have built a t least one : bazs object? Otherwise you wont see the nested form...

**Comment by rschooley** [comment]
Adding an empty baz displays a first row, but add still doesn't add another one.

The edit does not have a baz, it has an empty `#<ActiveRecord::Associations::CollectionProxy []>`

**Comment by ncri** [comment]
Ah, okay. Hard to debug this without having some real example code.

Do you have a script tag within the nested_fields_for? That is not supported, but would also generate a js error.

**Comment by rschooley** [comment]
I think I see what the issue is.  I have two forms on the same page, one for new, one for edit.  So there are blocks of nested_form_fields on the same page, and they don't seem to be happy about each other.

When I add a row in edit, the new form is being updated.  Looking at the JS there are some top level selectors which seem to be the cause.

**Comment by rschooley** [comment]
After looking at the source I found `data-insert-into`.  Using this appears to resolve this.

 The index is off (looking at first sel child count for index), but I don't think that will break anything.

**Comment by rschooley** [comment]
This is all fine now.  You may want to add documentation around multiple instances and the `data-insert-into` to the readme.

**Comment by ncri** [comment]
Glad you solved the issue. data-insert-into might have been added in a pull request, have to look into it and add it to the readme, yes...
