### ISSUE TITLE
Breaks when nested associated model is namespaced

### ISSUE THREAD

**Issue by tylerbodway** [ncri/nested_form_fields#51]
I get thrown an error when using the helper with an associated model that has been namespaced
```
class Company::Manager

  has_many :subordinates
  accept_nested_attributes_for :subordinates, allow_destroy: true

end
```
```
class Company::Subordinate

  belongs_to :manager

end
```
```
<%= f.nested_fields_for :subordinates do |ff| %>
  <div class="field">
    ... 
  </div>
<% end %>
```
##### Throws this error ... 
<tt>uninitialized constant Subordinate</tt>

**Comment by ncri** [comment]
Seems you are missing the class_name option somewhere:

Try:

```erb
<%= f.nested_fields_for :subordinates, class_name: "Company::Subordinate" do |ff| %>
    ... 
```

or 

```erb
<%= f.nested_fields_for :subordinates, class_name: "company/subordinate" do |ff| %>
    ... 
```

You might also have to add it at the has_many:

```ruby
has_many :subordinates, class_name: "Company::Subordinate"
```

**Comment by tylerbodway** [comment]
I had the class_name on the has_many, forgot to add that, but I didn't realize I needed the class_name on the nested_fields_for function, and that seemed to fix it for me!

Thanks for the assistance! Maybe a mention in the readme would help anyone else in that situation

**Comment by ncri** [comment]
Yes, I think so too. This came up a few times now.

**Comment by ncri** [comment]
Which option worked for you then? `class_name: "Company::Subordinate"` or `class_name: "company/subordinate"`? They might work both actually...

**Comment by tylerbodway** [comment]
I went with <tt>class_name: "Company::Subordinate"</tt> since that's more rails standard for namespaced models

**Comment by ncri** [comment]
I was just wondering if both works. I also prefer the class syntax.

**Comment by ncri** [comment]
I added a section about this in the readme.

**Comment by tylerbodway** [comment]
:+1:
