### ISSUE TITLE
Cannot access options[:parent_builder].nested_child_index

### ISSUE THREAD

**Issue by jgpignis** [ncri/nested_form_fields#52]
There is no access to index of nested attributes, because it is a private method.

**Comment by ncri** [comment]
Its a private method, which is not defined in this gem, but in the rails core. Why would you need access? 
Maybe this helps: https://github.com/ncri/nested_form_fields/issues/32

**Comment by jgpignis** [comment]
I need to retreive the nested child index to create a new entrance to each
nested hash, i did it by creating a new method in the gem which returns the
complete name (object[nested_object][nested_child_index])

Thanks for the help though

Jose Victor Garcia

Process and Operations Director

+52 656 136 0085 |  jgp@ignis.software |  Ciudad Juárez, Chihuahua, México
|

**Comment by ncri** [comment]
Glad you got it working, but patching the gem shouldn't be necessary for something like this.
If you can give me an example of your view code I could look into it, i don't quite understand yet what you are doing.

**Comment by jgpignis** [comment]
I will send you an example later

What i needed was to create in my view a new text_field for an attribute
which is not existant in my model, and then get the values in my controller

Jose Victor Garcia

Process and Operations Director

+52 656 136 0085 |  jgp@ignis.software |  Ciudad Juárez, Chihuahua, México
|


.

**Comment by jgpignis** [comment]
Hi,

 

My problem was 

1.       I have a nested form which creates a number field entry for a column :qty_received in my netsed model with the accepts_nested_attributes

2.       In the view the name of the number field is model[nested_model][nested_child_index][attribute] (ex. model[model1][0][qty_received])

a.       So the hash will be model => { netsed_attributes => { :qty_received => “value sent” } }

3.       The problem was that I needed to add an attribute to each of the same nested attributes (lote)

a.       For this the text_field should have the name model[model1][0][lote]

b.      Then the lote attribute will be added to the hash as it belongs to it

c.       So the problem was how to create a text_field_tag with the name of the number field without an attribute in my model?

 

= form_for @purchase_order do |f|

                  = f.nested_fields_for :item_list do |ff|

                    %tr

                      %td= ff.object.material

                      %td= ff.object.qty

                      %td= ff.object.qty_received

                      - if ff.object.qty_received != ff.object.qty

                          %td= ff.number_field :qty_received, required: true, min: 0, max: ff.object.qty, value:0, :step => 0.01

                          %td= text_field_tag "#{ff.test_index(ff.object)}[lote]"

 

Test_index is a method added by me in the gem as follows, which will return the string “model[model1][nested_child_index]” so I can add to the hash whichever attribute I want.

 

    def test_index association_name

      "#{object_name}"

    end

 

Jose Victor Garcia

Process and Operations Director

 

https://docs.google.com/uc?export=download&id=0B0NZsRPs-VSHbWtQZktPcDFIM1E&revid=0B0NZsRPs-VSHQzNCczBBazZkTTJaUCtUanVYZXkxS1UrQzdRPQ

 

  <https://www.facebook.com/IgnisSoftware> https://docs.google.com/uc?export=download&id=0B0NZsRPs-VSHb3hta0k3S012eDg&revid=0B0NZsRPs-VSHbUtFcjZ4REVFVFB0U1M4bkdhajE3V1FTMlA0PQ   <https://twitter.com/IgnisSoftware> https://docs.google.com/uc?export=download&id=0B0NZsRPs-VSHRU1GVDJSZkFQZlU&revid=0B0NZsRPs-VSHSFJMeFpJUDE3YUNMeXdUWFE1VzJmUWM5QW1zPQ  https://docs.google.com/uc?export=download&id=0B0NZsRPs-VSHb0VnOTAxWjFYQm8&revid=0B0NZsRPs-VSHbTVncmRtM1VjSEpjclBGTG91YzZESCtrdWVjPQ  https://docs.google.com/uc?export=download&id=0B0NZsRPs-VSHVWRWbksycHV2TFU&revid=0B0NZsRPs-VSHVVJ0VmMzWmZZY3A2dEpEQWhyakZybHJXbVdVPQ

 

  

+52 656 136 0085 |   <mailto:jgp@ignis.software> jgp@ignis.software |  Ciudad Juárez, Chihuahua, México | 

 

This e-mail message may contain confidential or legally privileged information and is intended only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. Anyone who communicates with us by e-mail is deemed to have accepted these risks. Company Name is not responsible for errors or omissions in this message and denies any responsibility for any damage arising from the use of e-mail. Any opinion and other statement contained in this message and any attachment are solely those of the author and do not necessarily represent those of the company.

**Comment by ncri** [comment]
The easiest solution for this case is actually to add a virtual attribute to the model, via attr_accessor:

    attr_accessor :lote

Then you can simply do:

    = ff.text_field :lote

in your form.

Alternatively you can get the index like this:

= f.nested_fields_for :item_list do |ff|
  - item_list_index = f.object.item_list.index(ff.object)

Its a bit odd by the way, that `item_list` has a singular name, as it is a has_many association.

**Comment by ncri** [comment]
Closing this as I haven't heard back from you.
