### ISSUE TITLE
Marked for deletion not persisted on re-render

### ISSUE THREAD

**Issue by JoeWoodward** [ncri/nested_form_fields#53]
If an object is marked for deletion but another object fails then the object marked for deletion is rendered again

i.e. 
I have nested comments that require the body attribute to be present
Three db persisted comments
mark one for deletion
add another without a body
click save
page renders with the three persisted comments and the new one with a validation error

**Comment by ncri** [comment]
I just released version 0.7.3. with experimental support for this.

The only change required on your end is that you need to add a _destroy field to your nested form:

    = ff.hidden_field :_destroy

Please let me know if it works for you.

**Comment by ncri** [comment]
Use 0.7.4. there was a char encoding issue in ruby 1.9.3 with 0.7.3.

**Comment by JoeWoodward** [comment]
Works perfectly. Thanks!

**Comment by ncri** [comment]
Glad to hear that! I will add a note to the readme.
