### ISSUE TITLE
Add field link does not work, closestChild gives error

### ISSUE THREAD

**Issue by Criticalstone** [ncri/nested_form_fields#54]
I get the eroor `Uncaught TypeError: $parsed_template.closestChild is not a function`
If i change the line 
`$child_templates = $parsed_template.closestChild('.form_template');`
to: 
`$child_templates = $parsed_template.closest('.form_template');`
It works flawless

**Comment by ncri** [comment]
Sounds like you might have something wrong in your js include order. You might also have jQuery included twice. I remember someone had an issue like this. Or do you have js inside your nested form? That can also cause issues. The modification you made will break some cases, I'm rather sure. `closestChild` looks at the children, `closest` at the parents.

**Comment by Criticalstone** [comment]
This is my current application.js
```
//= require jquery_ujs
//= require turbolinks
//= require bootstrap
//= require_tree .
//= require nested_form_fields
```

and my layouts include
```
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
```
This is the only place I include js.
I can't see where the issue lies

**Comment by ncri** [comment]
I dont see you requiring jquery, that seems to be the issue. Try adding it to the top:

    //= require jquery

**Comment by Criticalstone** [comment]
I actually missed that line
```
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require bootstrap
//= require_tree .
//= require nested_form_fields
```

**Comment by ncri** [comment]
does it work without bootstrap?

**Comment by Criticalstone** [comment]
No unfortunately not

**Comment by ncri** [comment]
I do remember someone had this issue before, but it hink they had some include wrong... Strange.

closestChild is actually defined in the nested_form_fields js. So there must be some naming conflict somehow. Something with jQuery is wrong. Is that a new app?

**Comment by Criticalstone** [comment]
I started the projekt two months ago or something

**Comment by Criticalstone** [comment]
I got it resolved thankfully.
In the bottom of my application layout I had some autogenerated script tag that included jquery again. 
Now it works as expected again :)

**Comment by ncri** [comment]
Great!
