### ISSUE TITLE
Add support for Turbolinks 5

### ISSUE THREAD

**Issue by jakubstraka** [ncri/nested_form_fields#57]
````
$(document).on "page:change", ->
    nested_form_fields.bind_nested_forms_links()
````

won't work as Turbolinks 5 changed the event to `turbolinks:load`

**Comment by ncri** [comment]
Haven't looked into  Turbolinks 5 yet. But I guess we can simply do `$(document).on "page:change turbolinks:load"` to stay backwards compatible?

**Comment by jakubstraka** [comment]
I think that should work.

That's how I call it

````
getReady = ->
  nested_form_fields.bind_nested_forms_links()

$(document).on('turbolinks:load ajaxComplete', getReady)
````

**Comment by ncri** [comment]
Done here: https://github.com/ncri/nested_form_fields/pull/59
