### ISSUE TITLE
pre populating form field value on add_nested_fields_link

### ISSUE THREAD

**Issue by gdlopez** [ncri/nested_form_fields#67]
Hello, not sure where to post this but I need to pre-populate a hidden_field. Is there a way that I can pass the field name and value on the add_nested_fields_link?

**Comment by ncri** [comment]
You can just set the field value inside the nested fields block, like you normally can

    fnested.hidden_field :xyz, value: val

Or just build the first nested object so that the field has the correct value. 

Or am I misunderstanding what you want to do? Is the value always the same?

**Comment by gdlopez** [comment]
Sorry for the misunderstanding. Here is a snippet of code of what I am trying to achieve. It is in HAML.
```haml
= f.nested_fields_for :z do |fnested|
  = fnested.hidden_field :y
  = fnested.number_field :x

-# I want to have this link create a nested :z form that sets the hidden_field :y value to 'abc' 
= f.add_nested_fields_link :z

-# Then I want to have this other link create a nested :z form that sets the 
-#   hidden_field :y value to 'xyz' 
= f.add_nested_fields_link :z
```

Is there any way of passing a block or something to f.add_nested_fields_link that in turn sets the value of the hidden_field?

**Comment by ncri** [comment]
Sorry for the late reply. Some ideas: You can use the fields_added.nested_form_fields event for this. If you attach the even to the link itself, $(this) should give you the link element. You could then store info about what data to pre-fill form fields with in the data hash of the add fields link. Or you make several event handlers depending on classes you give the links. And in each handler you can pre-fill the added fields with different data depending on the link class.
