### ISSUE TITLE
remove_nested_fields_link reloads page

### ISSUE THREAD

**Issue by murjax** [ncri/nested_form_fields#70]
I have a form that saves a `Report` with a one to many relationship with `Locomotive`. My nested form looks like this. 

```
<%= f.nested_fields_for :locomotives do |l| %>
  <div class="pure-control-group">
    <%= l.label(:number, "Locomotive #") %>
    <%= l.text_field(:number) %>
  </div>

  <div class="pure-control-group">
    <%= l.label(:loco_type, "Locomotive Type") %>
    <%= l.text_field(:loco_type) %>
  </div>

  <div class="pure-control-group">
    <%= l.label(:railroad, "Locomotive Railroad") %>
    <%= l.select :railroad, options_for_select(railroads_array) %>
  </div>

  <div class="pure-control-group">
    <%= l.remove_nested_fields_link %>
  </div>
<% end %>
					
<div class="pure-control-group">
  <%= f.add_nested_fields_link :locomotives %>
</div>
```
Whenever I click on the remove link, the page simply reloads. Debugging the JavaScript, I noticed it stops on line 42 in nested_form_fields.js.coffee.

`return false unless $.rails.allowAction($link)`

I am not sure if this returning false actually causes the page to reload, but I do know that the rest of the function is not being executed. I am currently using jquery-rails, jquery-ui-rails, coffee-rails, and coffee-script-source. I will provide additional code as requested, but I would like to know what causes that line in your JS to return false.

Thank you.

**Comment by ncri** [comment]
`rails.allowAction`is from jquery-ujs. It handles confirm dialogues:

You can find it here:

https://github.com/rails/jquery-ujs/blob/master/src/rails.js#L294

I haven't heard of your issue before, so I suggest you debug the function using the chrome dev tools.

**Comment by murjax** [comment]
Thanks for providing me the source of that function. I actually forgot to include `//= require jquery_ujs` in my application.js. You may close this issue.

**Comment by ncri** [comment]
Okay, great you solved it! :)
