### ISSUE TITLE
I18n Simple Form Translations don't work

### ISSUE THREAD

**Issue by mjfaga** [ncri/nested_form_fields#72]
It doesn't look like simple form translations are compatible with this library. 
### Models

``` ruby
class PrimaryObject
  has_many secondary_objects
end

class SecondaryObject
  belongs_to :primary_object
end
```
### My `simple_form.en.yml`:

``` ruby
en:
  simple_form:
    labels:
      primary_object:
        first_property: "First Property"
        secondary_objects:
          my_property: "Translated Label"
```
### My Form

``` ruby
= simple_form_for(@primary_object, url: primary_objects_path) do |f|
  = f.input :first_property
  = f.nested_fields_for :secondary_objects do |ff|
    = ff.input :name  
  = f.add_nested_fields_link :secondary_objects
```

In my controller, I'm defaulting secondary_objects in my controller with two `SecondaryObject.new`s:

``` ruby
class PrimaryObjectsController < ApplicationController
  def new
    @inquiry = PrimaryObject.new(
      secondary_objects: [
        SecondaryObject.new,
        SecondaryObject.new
      ]
    )
  end
end
```

 When the page initially loads and displays these two records using `nested_fields_for`, they are translated as I would expect. However, when I click the `add_nested_fields_link`, it adds a new field with the humanized version of the field, not the translated version. 

I should note that I can work around the problem by doing the following in my form file where I display SecondaryObject.name, but figured I'd see if there was anything you could do to get this working "out of the box":

``` ruby
= ff.input :name, label: I18n.t("simple_form.labels.primary_object.secondary_objects.name"
```

**Comment by ncri** [comment]
Oh, interesting, I haven't used this way of translating form labels yet. We use simple form a lot, but we stick to the Active Record way of looking up form translations:

```
activerecord:
  attributes:
    user:
      login: "Handle"
```

That works fine with nested_form_fields. I assume to get the gem to work the simple form way we need to dig into the source to see what is the issue. The nested_form_fields code is based on older rails form builder code which has changed a lot in the meanwhile. So probably the missing code that handles simple form style lookups can be discovered by debugging a non-nested rails simple form.

**Comment by ncri** [comment]
Thanks @darrenterhune so I will close this.
