### ISSUE TITLE
Adding a nested entry brakes the table layout

### ISSUE THREAD

**Issue by fchampreux** [ncri/nested_form_fields#79]
The result on following code is that the additional nested fields seem to be added all in the first column of the table, then splitting the rest of the table to the right.

  
    <table class="table table-striped table-condensed">
      <tr align="left">
        <th></th>
        <th><%= t('Name') %></th>
        <th><%= t('Description') %></th>
        <th><%= t('Type') %></th>
        <th><%= t('Size') %></th>
        <th><%= t('Precision') %> </th>
        <th><%= t('KeyCols') %></th>
        <th><%= t('PubCols') %></th>
      </tr>
      
    <%= f.nested_fields_for :skills do |column| %>
    
      <tr align="left">
        <td><%= column.remove_nested_fields_link %></td>
        <td><%= column.text_field :name %></td>
        <td><%= column.text_field :description %></td> 
        <td><%= column.collection_select :skill_type_id, @data_types_list, :id, :name %></td> 
        <td><%= column.text_field :skill_size %></td>
        <td><%= column.text_field :skill_precision %></td>
        <td><%= column.check_box :is_key %></td>
        <td><%= column.check_box :is_published %></td>
      </tr>
      
    <% end %>
    
    </table>
    
    <br/>
    
    <%= f.add_nested_fields_link :skills %>
    
    <br/>
    <br/>
    <div class="actions">
    <%= f.submit %>
    </div>

![screenshot](https://cloud.githubusercontent.com/assets/1111213/18980974/3351943e-86da-11e6-8f5c-89f29a30e2ca.png)

In the source of html page, </fieldset> tag may be inserted twice: 
[htmlSource.txt](https://github.com/ncri/nested_form_fields/files/502178/htmlSource.txt)

    
Thanks for help

**Comment by ncri** [comment]
Try adding `wrapper_tag` and if needed `wrapper_options` with your nested_fields call - it's in the readme. 

    f.nested_fields_for :skills, wrapper_tag: 'tr', wrapper_options: { class: 'left' } do |column|

should do if you remove the tr tag inside the nested_fields_for block.

**Comment by fchampreux** [comment]
OK, this works fine ! Great job !
Thanks !

**Comment by ncri** [comment]
Good to hear! I just see you actually didn't use a class 'left' but the align attribute so you need to adjust my code ;-)
