### ISSUE TITLE
Error when using Generate Rails4.1 and Ruby 2.1

### ISSUE THREAD

**Issue by honeycodedbear** [ncri/nested_form_fields#8]
here is my console log

maxs-air:nested_form_fields max$ rails g model user
/Users/max/Desktop/Code/AndroidRailsGCM/nested_form_fields/config/application.rb:10:in `<module:NestedFormFields>': uninitialized constant NestedFormFields::Rails::Application (NameError)
	from /Users/max/Desktop/Code/AndroidRailsGCM/nested_form_fields/config/application.rb:9:in `<top (required)>'
	from /Users/max/.rvm/gems/ruby-2.1.1/gems/spring-1.1.2/lib/spring/application.rb:82:in `require'
	from /Users/max/.rvm/gems/ruby-2.1.1/gems/spring-1.1.2/lib/spring/application.rb:82:in `preload'
	from /Users/max/.rvm/gems/ruby-2.1.1/gems/spring-1.1.2/lib/spring/application.rb:140:in `serve'
	from /Users/max/.rvm/gems/ruby-2.1.1/gems/spring-1.1.2/lib/spring/application.rb:128:in `block in run'
	from /Users/max/.rvm/gems/ruby-2.1.1/gems/spring-1.1.2/lib/spring/application.rb:122:in `loop'
	from /Users/max/.rvm/gems/ruby-2.1.1/gems/spring-1.1.2/lib/spring/application.rb:122:in `run'
	from /Users/max/.rvm/gems/ruby-2.1.1/gems/spring-1.1.2/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/max/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/max/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
maxs-air:nested_form_fields max$ 

Any ideas on what might be causing this issue?

**Comment by ncri** [comment]
Any updates on this? Have you tried with another app name? It looks like yours conflicts with the gem.
