### ISSUE TITLE
Showing Double Field when add field dynamic

### ISSUE THREAD

**Issue by ariawanzero** [ncri/nested_form_fields#84]
I want to ask when i'm using this gem why i always get 2 fields when i first time go to new page after action add new but when i refresh the browser the action work normal there is no error in javascript or in rails.  i'm using rails 5 in my project

**Comment by ncri** [comment]
So you click on the add nested fields button and it adds 2 nested forms instead of one? Can you clarify?

**Comment by ariawanzero** [comment]
update from me, i'm changing the place <%= javascript_include_tag "aplication", data-turbolink-track: true %> from body html to head html and it's work normal for nested form fields
but i think that can make my website load page slow because it's must render all javascript in head first  do you have solution for this?

**Comment by ncri** [comment]
Reason is probably that the if in the body, you keep adding event handlers when browsing, as turbolinks keeps the old events, only replacing the page body. At this time there is no way of adding the nested fields js in the body. But I can consider it for the future. However, probably many rails libraries won't work properly if you include the js in the body - although that is recommended. It's just not "the rails way" ;-). I'd like to find a solution for that too.

**Comment by sardaukar** [comment]
I'm having this problem too :| When I click on the add field link, I get 2 input items added

**Comment by ncri** [comment]
You also have your app.js in the body? Should be in the head.

**Comment by sardaukar** [comment]
I do have it in the body, yes. Is there any way to make it work?

**Comment by ncri** [comment]
You should put it in the head. Otherwise you might run into other js issues too. See my comment above. Or deactivate turbolinks. That should solve it too. But it can slow down your app quite a bit.

**Comment by ariawanzero** [comment]
i think that's not solution, javascript must keep under yield code. it's best option for perfomance, i think turbolinks make it like that so just try deactive that turbolinks.

**Comment by ncri** [comment]
No, turbolinks doesnt load js in the body. Turbolinks keeps the head between requests, only reloading the body html. You can read about it at the turbolinks repo.

**Comment by ariawanzero** [comment]
Turbolinks automatically fetches the page, swaps in its <body>, and merges its <head>, all without incurring the cost of a full page load. so all script in body swap if your js not loaded so it's stack with new js in body

**Comment by ncri** [comment]
Closing this for now. If anyone has an idea how to support having the script in the body instead of the head, you are welcome to make a pull request. ;-)
