### ISSUE TITLE
Deep nested with Rails 5

### ISSUE THREAD

**Issue by fidalgo** [ncri/nested_form_fields#85]
Hi!

I'm trying out a sample app, with Rails 5 and I can't get it working, I can only get the first level of nesting:

It's a simple app for demo purpose, where a `Product` has_many `Variants` which has_many `VariantFields`. The `accepts_nested_attributes_for` is set on every model. Am I missing something too obvious? 

Here is the view code

```
<%= form_for(product) do |f| %>
<% if product.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(product.errors.count, "error") %>
    prohibited this product from being saved:</h2>

  <ul>
    <% product.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :name, 'Product name' %>
  <%= f.text_field :name %>
</div>

<%= f.nested_fields_for :variants do |v|   %>
<div class="field">
  <%= v.remove_nested_fields_link  %>

  <%= v.label :name, 'Variant name' %>
  <%= v.text_field :name  %>

  <%= v.nested_fields_for :variant_fields do |vf| %>
  <%= vf.remove_nested_fields_link  %>

  <div class="field">
    <%= vf.label :name, 'VariantField name' %>
    <%= vf.text_field :name  %>
  </div>

  <%= f.add_nested_fields_link :variant_fields %>

  <% end %>
</div>
<% end %>

<%= f.add_nested_fields_link :variants %>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>
```
No errors on browser console or rails console.

**Comment by ncri** [comment]
Your second `f.add_nested_fields_link :variant_fields`should be `vf.add_nested_fields_link :variant_fields`. Other than that I don't see an issue. If this doesn't fix it, could you post the model code?

**Comment by fidalgo** [comment]
Ok, I'd already tried that and it won't work, so I've pushed the code to a repo hoping it helps finding the root of the problem. The repo is located at https://github.com/fidalgo/dependents

A million thanks for you time!

**Comment by ncri** [comment]
This works:

```
<%= f.nested_fields_for :variants do |v|   %>
<div class="field">
  <%= v.remove_nested_fields_link  %>

  <%= v.label :name, 'Variant name' %>
  <%= v.text_field :name  %>

  <%= v.nested_fields_for :variant_fields do |vf| %>
  <%= vf.remove_nested_fields_link  %>

  <div class="field">
    <%= vf.label :name, 'VariantField name' %>
    <%= vf.text_field :name  %>
  </div>

  <% end %>
  <%= v.add_nested_fields_link :variant_fields %>
</div>
<% end %>
```

**Comment by fidalgo** [comment]
Thanks a lot, I need glasses!

**Comment by ncri** [comment]
Welcome, I didn't see the issue too first ;-) Needed to be `v.add_nested_fields_link :variant_fields` instead of `f.add_nested_fields_link :variant_fields` and also the link needed to be outside the nested form. I like using slim or haml instead of erb as I see the nesting better due to indentation.
