### ISSUE TITLE
Unable to use __nested_field_for_replace_with_index__ in wrapper

### ISSUE THREAD

**Issue by daniel-sullivan** [ncri/nested_form_fields#91]
At present it's not possible to use __nested_field_for_replace_with_index__ in the wrapper tags of the nested fields. 

I've submitted a PR which allows this #90 

PS: This is my first time ever submitting a PR on GitHub, if I've made any mistakes in the process, please go easy on me :)

**Comment by ncri** [comment]
Thanks!
