### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by binhluong2012** [ncri/nested_form_fields#93]
![image](https://user-images.githubusercontent.com/29191103/29780707-eba67632-8c40-11e7-8f39-224da3f3ed40.png)
![image](https://user-images.githubusercontent.com/29191103/29780748-179c3dee-8c41-11e7-82b2-132c76f9ca19.png)

i'm using rails 5.1.3
coffee rails 4.2
jquery rails 4.3

**Comment by ncri** [comment]
Can you post your view code?

**Comment by murilomothsin** [comment]
I'm having the same error. My view code:

```
<div class="border-form-div col-md-10 col-md-offset-1">
  <%= simple_form_for(@position) do |f| %>
    <%= f.input :name %>
    <%= f.input :description, as: :text %>
    <%= f.add_nested_fields_link :competencies, class: 'btn btn-primary', role: 'button' %></p>
    <%= f.simple_fields_for :competencies do |builder| %>
      <%= builder.input :name %>
      <%= builder.input :value %>
    <% end %>
    <%= f.button :submit %>
  <% end %>
<div>
```


Can someone help me?

Best regards.

**Comment by ncri** [comment]
@murilomothsin You are not using nested_fields. Replace `simple_fields_for` with `nested_fields_for`.

**Comment by murilomothsin** [comment]
I'm so dumb, I should read the documentation better.

Thank you! :+1:

**Comment by ncri** [comment]
Ah, no problem, can happen... ;-)

**Comment by murilomothsin** [comment]
Can I close this issue?

**Comment by ncri** [comment]
I will close it.
