### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by hmc-cs-gwomark** [ncri/nested_form_fields#97]
Here is the parent model for which I'm trying to do nesting 

**orders.rb**
```
class Order < ApplicationRecord
    has_many :items
    accepts_nested_attributes_for :items, allow_destroy: true

    belongs_to :user
end
```
Here is it's corresponding controller
**orders_controllers.rb**
```
class OrdersController < ApplicationController
  before_action :authenticate_user!
  def index
    @orders = current_user.orders.all
    @order = current_user.orders.new
  end

  def new
    @order = current_user.orders.new
  end

  def destroy
    Order.find(params[:id]).destroy
    redirect_to root_path
  end

  def create
    @order = current_user.orders.new(order_parameters)
    if @order.save
      redirect_to root_path
    end
  end

  private

  def order_parameters
    params.require(:order).permit(:name, :id, items_attributes:[:strain,:_destroy,:id])
  end
end
```

And finally here is the code in my view
```
<%= form_for @order, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
  <%= f.text_field :name %>
  <%= f.add_nested_fields_link :items, 'Add Item', class: 'btn btn-primary', role: 'button' %>
  <% f.nested_fields_for :items do |ff| %>
    <%= ff.text_field :strain %>
    <%= ff.remove_nested_fields_link 'Remove Item', class: 'btn btn-danger', role: 'button'%>
  <% end %>
  <%= f.submit "Create" %>
<% end %>
```

The issue is that I keep getting an `Uncaught TypeError: Cannot read property 'replace' of undefined` whenever I click the 'Add Item' button.

**Comment by ncri** [comment]
Did you make sure you build at least one item? So before your form or in your controller do: 
```
@order.items.build if @order.items.none?
```

**Comment by mohdsameer** [comment]
its still the same issue.

**Comment by ncri** [comment]
@hmc-cs-gwomark did this solve your issue? @mohdsameer if you have the same js error, please post the relevant view, controller and model code here.

**Comment by hmc-cs-gwomark** [comment]
changing  <% f.nested_fields_for :items do |ff| %> to <=% f.nested_fields_for :items do |ff| %> did the trick. However I have approached another issue where all nested form fields are removed if I delete one.

**Comment by ncri** [comment]
Oh, good you solved the first issue. Didn't catch that, it's obvious now. Best you open a new issue for your other issue.
