### ISSUE TITLE
add_nested_fields_link prepend data instead of append 

### ISSUE THREAD

**Issue by LeCaoDat** [ncri/nested_form_fields#98]
Please help me!!!!

**Comment by ncri** [comment]
Hi there, you would want the nested fields appear on top of your other fields? That is not possible at the moment, but you could add the option using a data attribute, similar to "target":

https://github.com/ncri/nested_form_fields/blob/master/lib/assets/javascripts/nested_form_fields.js.coffee

Pull request welcome. ;-)

**Comment by LeCaoDat** [comment]
Thank you :crying_cat_face:
